esphome:
  name: zeltbox

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

web_server:
  port: 80

sensor:
  - platform: dht
    pin: D2
    model: DHT11
    temperature:
      name: "Temperatur"
      id: temperature
    humidity:
      name: "Luftfeuchtigkeit"
      id: "humidity"
    update_interval: 5s

  - platform: template
    name: "VPD"
    lambda: |-
      float temp_c = id(temperature).state;
      float humidity_x = id(humidity).state;
      float svp = 0.6108 * exp((17.27 * temp_c)/(temp_c + 237.3));
      float vp = (humidity_x/100)*svp;
      float vpd = svp - vp;
      return vpd;
    accuracy_decimals: 2
    update_interval: 5s